# Generated by Django 3.2.13 on 2022-05-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.CharField(default='non-user', max_length=100),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=250)),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='commented_on')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_app.comments')),
                ('root_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments_app.posts')),
            ],
        ),
    ]
