# Generated by Django 3.2.13 on 2022-05-21 17:32

from django.db import migrations


def create_dummy_posts(apps, schema_editor):
    Posts = apps.get_model('comments_app', 'Posts')
    Comments = apps.get_model('comments_app', 'Comments')
    user = 'MIGRATION-BOT'
    p1 = Posts(post_text='Post1', user=user)
    p2 = Posts(post_text='Post2', user=user)

    p1.save()
    p2.save()

    c1 = Comments(comment_text='post1/c1', root_post=p1)
    c1.save()

    c11 = Comments(comment_text='post1/c1/c11', root_post=p1, parent_comment=c1)
    c11.save()

    c2 = Comments(comment_text='post2/c1', root_post=p2)
    c2.save()


class Migration(migrations.Migration):
    dependencies = [
        ('comments_app', '0003_alter_comments_parent_comment'),
    ]

    operations = [
        migrations.RunPython(create_dummy_posts)
    ]
